### ISSUE TITLE
When I use backbutton (android) to hide the keyboard, the actions/footer doesn't hide together

### ISSUE THREAD

**Issue by Katekko** [diegoveloper/flutter_keyboard_actions#121]
I'm using that lib to track what the user is typing behind the keyboard.
![image](https://user-images.githubusercontent.com/13632735/95875977-fab67500-0d48-11eb-99d2-112d1493bc14.png)

![image](https://user-images.githubusercontent.com/13632735/95875721-b75c0680-0d48-11eb-8f3f-1b705ce5b51e.png)

![image](https://user-images.githubusercontent.com/13632735/95875756-c17e0500-0d48-11eb-84ba-e5bd0b42649a.png)

**Comment by diegoveloper** [comment]
nice catch, I'll check this bug. Are you using the latest version ?

**Comment by Katekko** [comment]
> nice catch, I'll check this bug. Are you using the latest version ?

Wow, so fast the answer.

Yes, the last version:  keyboard_actions: ^3.3.1

All my pubspec to you see the others packages that I have.

```
name: rps_online
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  get: ^3.13.2
  dio: ^3.0.10
  logger: ^0.9.4
  get_storage: ^1.3.1
  hive: ^1.4.4+1
  darq: ^0.4.0+1
  retrofit: ^1.3.4+1

  analyzer: ^0.39.16

  google_sign_in: ^4.5.4
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2

  web_socket_channel: ^1.1.0
  keyboard_actions: ^3.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.1
  json_serializable: ^3.5.0
  retrofit_generator: ^1.3.7+6
  hive_generator: ^0.7.2+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: 8BbitPusab
      fonts:
        - asset: assets/fonts/8-bit-pusab.ttf
```
