### ISSUE TITLE
Disabling Next + CloseButton should remove the button bar 

### ISSUE THREAD

**Issue by esDotDev** [diegoveloper/flutter_keyboard_actions#52]
When wanting to display just a footer, the top bar always renders, even if you've disabled both Next and CloseButton's.

**Comment by diegoveloper** [comment]
Hello, I was working recently on that feature, I did some breaking changes and I'm working on my `dev` branch now.

Check the image below
![Simulator Screen Shot - iPhone 8 - 2019-12-01 at 01 19 46](https://user-images.githubusercontent.com/4898256/69910401-e1c6fe80-13d8-11ea-96b1-6d1087eccc57.png)

As you can see you can use `footerBuilder` and hide the keyboard Bar, check the example on my dev branch and use the package in this way in your pubspec.yaml
```
  keyboard_actions:
    git:
      url: https://github.com/diegoveloper/flutter_keyboard_actions
      ref: dev
```

I'll publish this new version on Monday, feedback is welcome.
